### ISSUE TITLE
brainstorming

### ISSUE THREAD

**Issue by warittinan** [The-last-one-member/thelastonemenderNo1#25]
ให้ทุกคนคิดไอเดียคนละอันแล้วมาเสนอกันนะคับ

**Comment by warittinan** [comment]
ทำแอปมาเพื่อบอกที่อยู่และราคาสินค้า

**Comment by wachipor** [comment]
มีหน้าจอที่แสดงล็อคสินค้าแต่ละชิ้น

**Comment by Kittitath094** [comment]
ใช้สัญลักษณ์แสดงตัวสินค้า

**Comment by warittinan** [comment]
ให้มีพนักงานประจำล็อค

**Comment by ddreamktty** [comment]
ติดป้ายที่หน้าล็อค

**Comment by Phumisit** [comment]
ทำเเผนผังของล็อคสินค้าเรียงตามยี่ห้อเพื่อง่ายต่อการค้นหา

**Comment by wachipor** [comment]
มีหุ่นยนต์นำทางไปหาสินค้าที่ต้องการ

**Comment by Besutosama** [comment]
มีแผนที่รวมล๊อคตรงทางเข้า

**Comment by warittinan** [comment]
1.ทำแอปมาเพื่อบอกที่อยู่และราคาสินค้า
2.มีหน้าจอที่แสดงล็อคสินค้าแต่ละชิ้น
3.ใช้สัญลักษณ์แสดงแทนตัวสินค้า
4.ให้มีพนักงานประจำล็อค
5.ติดป้ายที่หน้าล็อค
6.ทำเเผนผังของล็อคสินค้าเรียงตามยี่ห้อเพื่อง่ายต่อการค้นหา
7.มีหุ่นยนต์นำทางไปหาสินค้าที่ต้องการ
8.มีแผนที่รวมล๊อคสินค้าตรงทางเข้า
