### ISSUE TITLE
idea election

### ISSUE THREAD

**Issue by warittinan** [The-last-one-member/thelastonemenderNo1#26]
1.ทำแอปมาเพื่อบอกที่อยู่และราคาสินค้า
2.มีหน้าจอที่แสดงล็อคสินค้าแต่ละชิ้น
3.ใช้สัญลักษณ์แสดงแทนตัวสินค้า
4.ให้มีพนักงานประจำล็อค
5.ติดป้ายที่หน้าล็อค
6.ทำเเผนผังของล็อคสินค้าเรียงตามยี่ห้อเพื่อง่ายต่อการค้นหา
7.มีหุ่นยนต์นำทางไปหาสินค้าที่ต้องการ
8.มีแผนที่รวมล็อคสินค้าตรงทางเข้า

**Comment by warittinan** [comment]
Rational choice(สมเหตุสมผลไม่แปลกใหม่)

**Comment by warittinan** [comment]
Most likely to delight(ถ้าทำได้เราจะมีความสุข)

**Comment by warittinan** [comment]
The darling(ชอบ อยากทำ น่าทำ)

**Comment by warittinan** [comment]
The long shot(ยากที่จะทำให้เสร็จ)

**Comment by wachipor** [comment]
โหวตทำแอปคร้าบ
