### ISSUE TITLE
Vote

### ISSUE THREAD

**Issue by warittinan** [The-last-one-member/thelastonemenderNo1#27]
ให้ทุกคนโหวตคนละ3อันนะคับ

**Comment by wachipor** [comment]
โหวตทำแอปคร้าบ

**Comment by wachipor** [comment]
-ทำแอปมาเพื่อบอกที่อยู่และราคาสินค้า
-มีหน้าจอที่แสดงล็อคสินค้าแต่ละชิ้น
-ใช้สัญลักษณ์แสดงแทนตัวสินค้า

**Comment by warittinan** [comment]
ทำแอปมาเพื่อบอกที่อยู่และราคาสินค้า

**Comment by warittinan** [comment]
มีหน้าจอที่แสดงล็อคสินค้าแต่ละชิ้น

**Comment by warittinan** [comment]
ใช้สัญลักษณ์แสดงแทนตัวสินค้า

**Comment by warittinan** [comment]
ให้มีพนักงานประจำล็อค

**Comment by warittinan** [comment]
ติดป้ายที่หน้าล็อค

**Comment by warittinan** [comment]
ทำเเผนผังของล็อคสินค้าเรียงตามยี่ห้อเพื่อง่ายต่อการค้นหา

**Comment by warittinan** [comment]
มีหุ่นยนต์นำทางไปหาสินค้าที่ต้องการ

**Comment by warittinan** [comment]
มีแผนที่รวมล๊อคสินค้าตรงทางเข้า

**Comment by warittinan** [comment]
สรุปทำอันนี้นะคับทุกคน
ทำแอปมาเพื่อบอกที่อยู่และราคาสินค้า

**Comment by ddreamktty** [comment]
โอเคค้าบบบบบ

**Comment by wachipor** [comment]
อาเครคับ
