### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by wachipor** [The-last-one-member/thelastonemenderNo1#28]
มีใครทำได้บ้างมั้ยครับ

**Comment by ddreamktty** [comment]
เราทำไม่เป็น

**Comment by Besutosama** [comment]
ผมทำไม่ค่อยเป็นครับ

**Comment by warittinan** [comment]
เติ้ลว่าทำได้อยู่เดี๋ยวลองดูนะ เดี๋ยวเติ้ลทำเสร็จจะเอาให้ดู

**Comment by wachipor** [comment]
สุดยอดเลยครับ

**Comment by Besutosama** [comment]
โอเคเลยครับ

**Comment by ddreamktty** [comment]
เคเลยย

**Comment by warittinan** [comment]
https://www.figma.com/proto/Ps2wBP7fR1nWPJedV0DiNs/%E0%B8%95%E0%B8%B1%E0%B8%A7%E0%B8%88%E0%B8%A3%E0%B8%B4%E0%B8%87?node-id=1%3A4&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A4

**Comment by warittinan** [comment]
ทำเสร็จแล้วคับ

**Comment by wachipor** [comment]
สวยมากๆเลยเพื่อน

**Comment by Besutosama** [comment]
โอเคมากเลยนะครับเนี่ย
