### ISSUE TITLE
scenario/script

### ISSUE THREAD

**Issue by wachipor** [The-last-one-member/thelastonemenderNo1#30]
ใครคิดเนื้อเรื่องออกบ้างครับ

**Comment by Kittitath094** [comment]
เราเอง

**Comment by Kittitath094** [comment]
สถานที่ Supermaket แห่งหนึ่ง
เรา:สวัสดีครับคุณป้า ทำไรอยู่ครับ
ป้า: ออ.. พอดีกำลังหาวัตถุดิบทำอาหารอยู่ค่ะ หาเท่าไรก็หาไม่เจอค่ะ
เรา:ให้ผมช่วยนะครับคุณป้า
ป้า:ได้ค่ะ ขอบคุณนะคะ
เรา:นี่ไงครับ เจอแล้ว
ป้า:ขอบคุณนะคะ
ป้า: ป้าว่าหาของแต่ละอย่างหายากมากเลยนะ อยากมีตัวช่วยดีๆบ้าง จะได้หาของในsupermarketง่ายขึ้น
เรา:ป้าเคยประสบปัญหาในการหาที่ต้องการหาของยากหรือหาไม่เจอไหมครับ
ป้า: เคยค่ะ  
เรา:นี่ครับ ผมมีตัวช่วยในการหาของง่ายขึ้นด้วยครับ
ป้า:ยังไงคะ น่าสนใจจัง
เรา:สามารถดูราคาและที่อยู่ของสินค้า หาของง่ายขึ้นและประหยัดเวลาด้วยครับ ป้าสามารถพิมพ์หาของที่ต้องการได้เลย
ป้า:ดีจังเลย ป้าต้องลองใช้แล้วละ!!

**Comment by Besutosama** [comment]
โอเคเลยนะครับ
