### ISSUE TITLE
story board

### ISSUE THREAD

**Issue by wachipor** [The-last-one-member/thelastonemenderNo1#34]
มาแบ่งงานกันๆ

**Comment by ddreamktty** [comment]
เราทำอันนี้นะ
เรา:สวัสดีครับคุณป้า ทำไรอยู่ครับ
ป้า: ออ.. พอดีกำลังหาวัตถุดิบทำอาหารอยู่ค่ะ หาเท่าไรก็หาไม่เจอค่ะ

**Comment by Kittitath094** [comment]
เราทำ
เรา:นี่ไงครับ เจอแล้ว
ป้า:ขอบคุณนะคะ

**Comment by wachipor** [comment]
ป้า: ป้าว่าหาของแต่ละอย่างหายากมากเลยนะ อยากมีตัวช่วยดีๆบ้าง จะได้หาของในsupermarketง่ายขึ้น
เรา:ป้าเคยประสบปัญหาในการหาที่ต้องการหาของยากหรือหาไม่เจอไหมครับ
ป้า: เคยค่ะ

**Comment by Besutosama** [comment]
เดี๋ยวเราทำ
เรา:นี่ครับ ผมมีตัวช่วยในการหาของง่ายขึ้นด้วยครับ
ป้า:ยังไงคะ น่าสนใจจัง
เรา:สามารถดูราคาและที่อยู่ของสินค้า หาของง่ายขึ้นและประหยัดเวลาด้วยครับ ป้าสามารถพิมพ์หาของที่ต้องการได้เลย
ป้า:ดีจังเลย ป้าต้องลองใช้แล้วละ!!

**Comment by Kittitath094** [comment]
เราทำเพิ่ม
เรา:ให้ผมช่วยนะครับคุณป้า
ป้า:ได้ค่ะ ขอบคุณนะคะ
