### ISSUE TITLE
feedback matrix

### ISSUE THREAD

**Issue by warittinan** [The-last-one-member/thelastonemenderNo1#40]
ให้เพื่อนๆลองดูว่าprototypeแล้วลองคอมเม้นกันคับ

**Comment by wachipor** [comment]
เราว่าปรับตัวหนังสือนิดหน่อยมั้ย

**Comment by ddreamktty** [comment]
โอเคนะๆ

**Comment by Besutosama** [comment]
โอเคแล้วครับ

**Comment by Kittitath094** [comment]
โอเครแล้วครับ

**Comment by ddreamktty** [comment]
อยากให้ช่องค้นหา เพิ่มการค้นหาจากสียงได้

**Comment by ddreamktty** [comment]
เพิ่มภาพรวมของทุกล็อค เหมือนภาพที่รวมทุกล็อค เอาไว้ดูรวมๆน่ะ

**Comment by ddreamktty** [comment]
อยากให้เพิ่มว่าของเเต่ละชิ้นมีสต๊อกเท่าไหร่ หรือ0ชิ้นสำหรับของหมด
